//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int PersonelID { get; set; }
        public Nullable<int> SubeID { get; set; }
        public string Sifre { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Sube Sube { get; set; }
    }
}
