//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int SeferID { get; set; }
        public int KoltukNo { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriCinsiyet { get; set; }
        public Nullable<double> Ucret { get; set; }
        public string IslemZamani { get; set; }
        public string IslemTipi { get; set; }
        public string BiletTipi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual SubeBilet SubeBilet { get; set; }
        public virtual Sefer Sefer { get; set; }
    }
}
