//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValeDBEntities : DbContext
    {
        public ValeDBEntities()
            : base("name=ValeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Otobus> Otobus { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Sefer> Sefer { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<SubeBilet> SubeBilet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
