//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sefer
    {
        public int SeferID { get; set; }
        public string KalkisSehri { get; set; }
        public string VarisSehri { get; set; }
        public Nullable<int> OtobusID { get; set; }
        public Nullable<int> SoforID { get; set; }
        public Nullable<int> MuavinID { get; set; }
        public Nullable<System.DateTime> KalkisZamani { get; set; }
        public Nullable<int> TahminiSure { get; set; }
    
        public virtual Otobus Otobus { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Personel Personel1 { get; set; }
    }
}
