//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubeBilet
    {
        public int SeferID { get; set; }
        public int KoltukNo { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Bilet Bilet { get; set; }
    }
}
